# Generated by Django 3.0.4 on 2020-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrecord',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
