# Generated by Django 3.0.4 on 2020-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_businessrecord_instagram_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='donor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
